module.exports.Success = require('./200')
module.exports.BadRequest = require('./400');
module.exports.AuthError= require('./401');
module.exports.RequireRefreshToken = require('./402');
module.exports.Forbidden = require('./403');
module.exports.NotFound = require('./404');
module.exports.Conflict = require('./409');
module.exports.ValidationError = require('./422');
module.exports.ServerError= require('./500');